<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php /** @var Adyen_Payment_Block_Form_Cc $this */; ?>
<?php $_code = $this->getMethodCode();
$originKey = $this->getOriginKeys();
?>


<ul id="payment_form_<?php echo $_code ?>" style="display:none;">

    <div class="checkout-container">
        <div class="form-div">
            <div class="js-chckt-pm__pm-holder">
                <input type="hidden" name="txvariant" value="card"/>
                <div class="input-container">
                    <span class="input-label"><?php echo $this->__('Name on Card') ?></span>
                    <span class="input-field required-entry"> <input type="text"
                                                                     title="<?php echo $this->__('Name on Card') ?>"
                                                                     class="input-field required-entry"
                                                                     autocomplete="cc-name"
                                                                     id="<?php echo $_code ?>_cc_owner" <?php echo("name=\"payment[cc_owner]\""); ?>
                                                                     value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"
                                                                     maxlength="100"/>  </span>

                </div>
                <div class="input-container">
                    <span class="input-label">Card number:</span>
                    <span class="input-field" data-cse="encryptedCardNumber"></span>
                </div>
                <div class="input-container">
                    <span class="input-label">Expiry month:</span>
                    <span class="input-field" data-cse="encryptedExpiryMonth"></span>
                </div>
                <div class="input-container">
                    <span class="input-label">Expiry year:</span>
                    <span class="input-field" data-cse="encryptedExpiryYear"></span>
                </div>
                <div class="input-container">
                    <span class="input-label label-security-code">Security code:</span>
                    <span class="input-field" data-cse="encryptedSecurityCode"</span>
                </div>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc"
                               value="1" checked/>
                        <label for="<?php echo $_code ?>_store_cc"><em>*</em><?php echo $this->__('Remember these details') ?>
                        </label>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" name="payment[encrypted_number]" id="encryptedCardNumber" value="">
        <input type="hidden" name="payment[encrypted_expiry_month]" id="encryptedExpiryMonth" value="">
        <input type="hidden" name="payment[encrypted_expiry_year]" id="encryptedExpiryYear" value="">
        <input type="hidden" name="payment[encrypted_cvc]" id="encryptedSecurityCode" value="">
    </div>
</ul>
<input type="hidden" id="<?php echo $_code ?>_encrypted_form_expiry_generationtime" value="<?php echo date("c"); ?>"
       data-encrypted-name="generationtime"/>
<script type="text/javascript">
    var securedFields =
        {
            originKey: "<?php echo $originKey;?>",
            rootNode: '.form-div',
            allowedDOMAccess: false,
            securedFieldStyling: {
                placeholders: {
                    encryptedCardNumber: '4111 1111 1111 1111',
                    encryptedExpiryMonth: '10',
                    encryptedExpiryYear: '20',
                    encryptedSecurityCode: '737'
                }
            },
            callbacks: {
                onFieldValid: function (result) {
                    document.getElementById(result.encryptedFieldName).value = result.blob;
                }
            }
        };
    new csf(securedFields);
</script>
