<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php /** @var Adyen_Payment_Block_Form_Cc $this */; ?>
<?php $_code = $this->getMethodCode();
$originKey = $this->getOriginKey();
?>


<ul id="payment_form_<?php echo $_code ?>" style="display:none;">

    <div class="checkout-container">
        <div class="form-div">
            <div class="js-chckt-pm__pm-holder">
                <input type="hidden" name="txvariant" value="card"/>
                <div class="input-container">
                    <span class="input-label"><?php echo $this->__('Name on Card') ?></span>
                    <span class="input-field required-entry"> <input type="text"
                                                                     title="<?php echo $this->__('Name on Card') ?>"
                                                                     class="input-field required-entry"
                                                                     autocomplete="cc-name"
                                                                     id="<?php echo $_code ?>_cc_owner" <?php echo("name=\"payment[cc_owner]\""); ?>
                                                                     value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"
                                                                     maxlength="100"/>  </span>

                </div>
                <div class="input-container">
                    <span class="input-label">Card number:</span>
                    <span class="input-field" data-cse="encryptedCardNumber"></span>
                </div>
                <div class="input-container">
                    <span class="input-label">Expiry month:</span>
                    <span class="input-field" data-cse="encryptedExpiryMonth"></span>
                </div>
                <div class="input-container">
                    <span class="input-label">Expiry year:</span>
                    <span class="input-field" data-cse="encryptedExpiryYear"></span>
                </div>
                <?php if( $this->hasVerification()):?>
                <div class="input-container">
                    <span class="input-label label-security-code">Security code:</span>
                    <span class="input-field" data-cse="encryptedSecurityCode"></span>
                </div>
                <?php endif; ?>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc"
                               value="1" checked/>
                        <label for="<?php echo $_code ?>_store_cc"><em>*</em><?php echo $this->__('Remember these details') ?>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <?php if($this->hasInstallments()): ?>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_installments" name="payment[additional_data]" class="number required-entry">
                            <?php foreach ($this->getPossibleInstallments() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
        <?php endif;?>

        <input type="hidden" name="payment[encrypted_number]" id="encryptedCardNumber" value="">
        <input type="hidden" name="payment[encrypted_expiry_month]" id="encryptedExpiryMonth" value="">
        <input type="hidden" name="payment[encrypted_expiry_year]" id="encryptedExpiryYear" value="">
        <input type="hidden" name="payment[encrypted_cvc]" id="encryptedSecurityCode" value="">
    </div>
</ul>
<input type="hidden" id="<?php echo $_code ?>_encrypted_form_expiry_generationtime" value="<?php echo date("c"); ?>"
       data-encrypted-name="generationtime"/>

<script type="text/javascript">

    var ajaxReq;
    function getInstallments(variant) {
        // get the installments for this cardtype
        var ccType = variant;
        var url = '<?php echo  Mage::helper('adminhtml')->getUrl('adminhtml/GetInstallmentsAdmin'); ?>';
        if (ajaxReq && ajaxReq.readystate != 4) {
            ajaxReq.transport.abort();
        }

        ajaxReq = new Ajax.Request(url, {
            parameters: {ccType: ccType, isAjax: 1, method: 'POST'},
            onSuccess: function (transport) {

                if (transport.status == 200) {

                    // get current selected installment
                    var currentSelectedInstallment = document.getElementById('<?php echo $_code ?>_installments').getValue();

                    // clear the select box
                    document.getElementById('<?php echo $_code ?>_installments').options.length = 0;

                    var response = transport.responseText.evalJSON();

                    var sel = false;
                    for (var key in response) {

                        // change the installments
                        var opt = document.createElement('option');
                        opt.text = response[key]
                        opt.value = key;
                        // check if selected installment is still available
                        if (currentSelectedInstallment == key) {
                            sel = true;
                        }
                        $('<?php echo $_code ?>_installments').options.add(opt);
                    }

                    if (sel == true && currentSelectedInstallment) {
                        document.getElementById('adyen_cc_installments').value = currentSelectedInstallment;
                    }
                }
            },
            onFailure: function () {
                alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
            }
        });
    }


    function initiateSecuredFields() {
        var securedFields = csf(
            {
                configObject: {
                    originKey: "<?php echo $originKey;?>",
                },
                rootNode: 'body',
                allowedDOMAccess: false,
                recurringCardIndicator: 'oneclick_',
                paymentMethods: {
                    card: {
                        placeholders: {
                            encryptedCardNumber: '4111 1111 1111 1111',
                            encryptedExpiryMonth: '10',
                            encryptedExpiryYear: '20',
                            encryptedSecurityCode: '737'
                        }

                    }
                }
            }
        );
        securedFields.onBrand(function (brandObject) {
            if (brandObject.brand) {
                getInstallments(brandObject.brand);
            }
        });
        securedFields.onFieldValid(function (result) {
            if (result.txVariant == 'card') {
                document.getElementById(result.encryptedFieldName).value = result.blob;
            }
            else {
                document.getElementById(result.encryptedFieldName.concat(result.txVariant.replace("oneclick_", ""))).value = result.blob;
            }
        });
    }
    var secf = document.createElement("script");
    <?php $adyenHelper = Mage::helper('adyen'); ?>
    <?php if($adyenHelper->getConfigDataDemoMode()): ?>
    secf.src = "https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSecuredFields.1.3.0.min.js";
    <?php else : ?>
    secf.src = "https://checkoutshopper-live.adyen.com/checkoutshopper/assets/js/sdk/checkoutSecuredFields.1.3.0.min.js";
    <?php endif; ?>
    secf.type = "text/javascript";
    secf.onload = initiateSecuredFields;
    document.body.appendChild(secf);

</script>
