<script type="text/javascript">
    var secf = document.createElement("script");
    <?php $adyenHelper = Mage::helper('adyen');

    ?>
    <?php if($adyenHelper->getConfigDataDemoMode()): ?>
    secf.src = "https://checkoutshopper-test.adyen.com/checkoutshopper/assets/js/sdk/checkoutSecuredFields.1.3.0.js";
    <?php else : ?>
    secf.src = "https://checkoutshopper-live.adyen.com/checkoutshopper/assets/js/sdk/checkoutSecuredFields.1.3.0.js";
    <?php endif; ?>
    secf.type = "text/javascript";
    document.body.appendChild(secf);
</script>