<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php
/** @var Adyen_Payment_Block_Form_Cc $this */
$_code = $this->getMethodCode();
$originKey = $this->getOriginKey();
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li class="adyen_payment_creditcard_labels">
        <?php $count = 0;
        foreach ($this->getCcAvailableTypes() as $_typeCode => $_data): ?>
            <?php $_filename = $this->getSkinUrl('images/adyen/' . strtolower($_data['code_alt']) . '_small.png'); ?>
            <img id="cc_type_<?php echo $count; ?>" width="40" height="22" src="<?php echo $_filename; ?>" alt=""
                 class="mid"/>
            <?php ++$count;
        endforeach; ?>
        <input type="hidden" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" value=""/>
    </li>

    <?php echo $this->getChildHtml() ?>

    <?php if ($this->hasInstallments()): ?>
        <li class="adyen_payment_input_fields adyen_payment_input_fields_cc_installments">
            <label for="<?php echo $_code ?>_installments"
                   class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_installments" name="payment[additional_data]"
                            class="number required-entry">
                        <?php foreach ($this->getPossibleInstallments() as $k => $v): ?>
                            <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
    <?php endif; ?>

    <?php if ($this->canCreateBillingAgreement()): ?>
        <script type="text/javascript">
            // don't show save cc for guest checkout. Only possible to detect with javascript
            if ($('login:guest') && $('login:guest').checked) {
                $('adyen-remember-details').hide();
            }
        </script>
    <?php endif; ?>


    <script type="text/javascript">
        var alt_types = <?php echo json_encode(array_column($this->getCcAvailableTypes(), 'code_alt')); ?>;

        function cardSetCardBrand(selectedCard, greyInactive, alt_types) {
            for (var i = 0; i < alt_types.length; ++i) {
                var imageId = 'cc_type_' + i;
                if (selectedCard != null && alt_types[i] == selectedCard) {
                    // remove class
                    $(imageId).removeClassName('grey');
                    // set hidden field cc type for installments
                    $('<?php echo $_code ?>_cc_type').setValue(selectedCard);
                } else {
                    if (greyInactive) {
                        // add class
                        $(imageId).addClassName('grey');
                    } else {
                        // remove class
                        $(imageId).removeClassName('grey');
                    }
                }
                if (selectedCard == "card") {
                    $('<?php echo $_code ?>_cc_type').setValue("");
                }
                document.getElementById(imageId).style.display = "inline";
            }

            <?php if($this->hasInstallments()): ?>
            if (selectedCard != null) {
                getInstallments(selectedCard);
            }
            <?php endif; ?>

        }

        var ajaxReq;

        function getInstallments(variant) {
            // get the installments for this cardtype
            var ccType = variant;
            var url = '<?php echo $this->getUrl('adyen/GetInstallments', array('_secure' => true)); ?>';
            if (ajaxReq && ajaxReq.readystate != 4) {
                ajaxReq.transport.abort();
            }

            ajaxReq = new Ajax.Request(url, {
                parameters: {ccType: ccType, isAjax: 1, method: 'POST'},
                onSuccess: function (transport) {

                    if (transport.status == 200) {

                        // get current selected installment
                        var currentSelectedInstallment = document.getElementById('<?php echo $_code ?>_installments').getValue();

                        // clear the select box
                        document.getElementById('<?php echo $_code ?>_installments').options.length = 0;

                        var response = transport.responseText.evalJSON();
                        var sel = false;
                        for (var key in response) {

                            // change the installments
                            var opt = document.createElement('option');
                            opt.text = response[key]
                            opt.value = key;
                            // check if selected installment is still available
                            if (currentSelectedInstallment == key) {
                                sel = true;
                            }
                            $('<?php echo $_code ?>_installments').options.add(opt);
                        }

                        if (sel == true && currentSelectedInstallment) {
                            document.getElementById('adyen_cc_installments').value = currentSelectedInstallment;
                        }
                    }
                },
                onFailure: function () {
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                }
            });
        }

        function initiateSecuredFields() {
            var cardGroupTypes = alt_types.slice();
            //cardDefault is added to since the onBrand callback is not fired with only one Type
            cardGroupTypes.push('cardDefault');
            var styleObject = {
                error: {color: 'red'}
            };
            var securedFields = csf(
                {
                    configObject: {
                        originKey: "<?php echo $originKey;?>",
                        cardGroupTypes: cardGroupTypes
                    },
                    rootNode: 'body',
                    allowedDOMAccess: false,
                    recurringCardIndicator: 'oneclick_',
                    paymentMethods: {
                        card: {
                            sfStyles: styleObject,
                            placeholders: {
                                encryptedCardNumber: '4111 1111 1111 1111',
                                encryptedExpiryMonth: '10',
                                encryptedExpiryYear: '20',
                                encryptedSecurityCode: '737'
                            }

                        }
                    }
                }
            );
            securedFields.onBrand(function (brandObject) {
                if (brandObject.brand) {
                    cardSetCardBrand(brandObject.brand, true, alt_types);
                }
            });
            securedFields.onFieldValid(function (result) {
                if (result.txVariant == 'card') {
                    document.getElementById(result.encryptedFieldName).value = result.blob;
                }
                else {
                    document.getElementById(result.encryptedFieldName.concat(result.txVariant.replace("oneclick_", ""))).value = result.blob;
                }
            });
            securedFields.onError(function (errorObject) {
                if (errorObject.error != "") {
                    document.getElementById(errorObject.fieldType).value = "";
                    element = document.getElementById("advice-required-entry-".concat(errorObject.fieldType));
                    element.update('<?php echo $this->__('The field is not valid.')?>');
                    element.style.opacity = 1;
                    element.show();
                }
                else {
                    element = document.getElementById("advice-required-entry-".concat(errorObject.fieldType));
                    element.update('<?php echo $this->__('This is a required field.')?>');
                    element.hide();
                }
            });
            securedFields.onAllValid(function (allValidObject) {
                if (allValidObject.allValid) {
                    document.getElementById("allValidcard").value = true;
                }
                else {
                    document.getElementById("allValidcard").value = "";
                }
            });
        }

        var secf = document.createElement("script");
        <?php $adyenHelper = Mage::helper('adyen'); ?>
        secf.src = "<?php echo $adyenHelper->getSecuredFieldsURL();?>";
        secf.type = "text/javascript";
        secf.onload = initiateSecuredFields;
        document.body.appendChild(secf);

    </script>
    <li>
        <div class="checkout-container" id="adyen-cc-checkout-container">
            <div class="form-div">
                <div class="js-chckt-pm__pm-holder">
                    <input type="hidden" name="txvariant" value="card"/>
                    <div class="input-container">
                        <span class="input-label"><?php echo $this->__('Name on Card') ?></span>
                        <div class="input-field required"><input type="text"
                                                                 title="<?php echo $this->__('Name on Card') ?>"
                                                                 class="input-field required-entry"
                                                                 autocomplete="cc-name"
                                                                 id="<?php echo $_code ?>_cc_owner" <?php echo("name=\"payment[cc_owner]\""); ?>
                                                                 value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"
                                                                 maxlength="100"/>
                        </div>
                    </div>
                    <div class="validation-advice" id="advice-required-entry-adyen_cc_cc_owner"
                         style="display: none;"><?php echo $this->__('This is a required field.') ?></div>
                    <div class="input-container">
                        <span class="input-label"><?php echo $this->__('Card number') ?>:</span>
                        <span class="input-field required-entry" data-cse="encryptedCardNumber"></span>
                    </div>
                    <div class="validation-advice" id="advice-required-entry-encryptedCardNumber"
                         style="display: none;"><?php echo $this->__('This is a required field.') ?>
                    </div>
                    <div class="input-container">
                        <span class="input-label"><?php echo $this->__('Expiry month') ?>:</span>
                        <span class="input-field" data-cse="encryptedExpiryMonth"></span>
                    </div>
                    <div class="validation-advice" id="advice-required-entry-encryptedExpiryMonth"
                         style="display: none;"><?php echo $this->__('This is a required field.') ?></div>
                    <div class="input-container">
                        <span class="input-label"><?php echo $this->__('Expiry year') ?>:</span>
                        <span class="input-field" data-cse="encryptedExpiryYear"></span>
                    </div>
                    <div class="validation-advice" id="advice-required-entry-encryptedExpiryYear"
                         style="display: none;"><?php echo $this->__('This is a required field.') ?></div>
                    <div class="input-container">
                        <span class="input-label label-security-code"><?php echo $this->__('Security code') ?>:</span>
                        <span class="input-field" data-cse="encryptedSecurityCode"></span>
                    </div>
                    <div class="validation-advice" id="advice-required-entry-encryptedSecurityCode"
                         style="display: none;"><?php echo $this->__('This is a required field.') ?></div>
                    <?php if ($this->canCreateBillingAgreement()): ?>
                        <div class="input-box" id="adyen-remember-details">
                            <div class="v-fix">
                                <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc"
                                       value="1" checked/>
                                <label for="<?php echo $_code ?>_store_cc"><em>*</em><?php echo $this->__('Remember these details') ?>
                                </label>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <input type="hidden" class="required-entry" name="payment[encrypted_number]" id="encryptedCardNumber"
                   value="">
            <input type="hidden" class="required-entry" name="payment[encrypted_expiry_month]" id="encryptedExpiryMonth"
                   value="">
            <input type="hidden" class="required-entry" name="payment[encrypted_expiry_year]" id="encryptedExpiryYear"
                   value="">
            <input type="hidden" class="required-entry" name="payment[encrypted_cvc]" id="encryptedSecurityCode"
                   value="">
            <input type="hidden" class="required-entry" name="allValidcard" id="allValidcard" value="">
            <div class="validation-advice" id="advice-required-entry-allValidcard"
                 style="display: none;"><?php echo $this->__('Please check that all the required fields are valid.') ?></div>

        </div>
    </li>
</ul>
