<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php
/** @var Adyen_Payment_Block_Form_Cc $this */
$_code = $this->getMethodCode();
?>
<ul class="form-list paymentsage" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <div>
            <ul class="alignCenter marginBottom" style="max-width: 600px; margin-right: auto; margin-left: auto;font-family: Arial,Helvetica,sans-serif">
                <li>Voici l'échéancier de votre paiement en 3x sans frais:</li>
                <li>1er paiement (aujourd'hui) : 
                <?php 
                    $cartTotal =  Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal(); 
                     
                    $installments = number_format(((int)$cartTotal/3),2);
                    $totalInstallments = $installments * 3;
                    $remainingCents = $cartTotal - $totalInstallments;
                    
                    $firstInstallment = $installments + $remainingCents;
                    echo '<strong>'.$this->helper('checkout')->formatPrice($firstInstallment).'</strong>';
                ?>     
                </li>
                <?php 
                    $todaysDate = date('Y-m-d');
                    $data = array(
                        'effectivedate' => $todaysDate,
                        'duration'      => 2
                    );
                    function getPaymentDates(array $data)
                    {   
                        $begin = new DateTime($data['effectivedate']);
                        $period = new DatePeriod(
                            $begin,
                            new DateInterval('P1M'),
                            (int) $data['duration']
                        );
                        
                        $clean = array();
                        $last = (int) $begin->format('m');
                        foreach ($period as $date)
                        {
                            while($last != $date->format('m'))
                                $date->modify('-1 day');//subtract days until we get to the last day of the previous month...
                            $clean[] = $date->format('d.m.Y');
                            if (++$last > 12)
                                $last = 1;//no 13th month, of course...
                        }
                        return $clean;
                    }
                    $duedate = getPaymentDates($data);
                ?>
                <li>2e paiement ( <?php echo $duedate[1]; ?> ) : 
                <?php echo '<strong>'.$this->helper('checkout')->formatPrice($installments).'</strong>'; ?>
                </li>
                <li class="marginBottom">3e paiement ( <?php echo $duedate[2]; ?> ) : 
                <?php echo '<strong>'.$this->helper('checkout')->formatPrice($installments).'</strong>'; ?>
                </li>
                <li>
                    Ces échéances seront débitées automatiquement sur votre carte de paiement aux dates indiquées ci-dessus.<br>
                    Coût total du crédit : <strong>0 €</strong>
                <li>
                    <strong>NB : En réglant en 3x sans frais, votre commande pourra nécessiter jusqu'à 24H supplémentaires de traitement afin de permettre à nos équipes de traiter correctement votre dossier.
                    </strong>
                </li>
                <li>
                    <strong>Un crédit vous engage et doit être remboursé.<br>
                    Vérifiez vos capacités de remboursement avant de vous engager.
                    </strong>
                </li>
                <li>
                    <strong>
                        Attention : Des mensualités non honorées pourraient avoir des conséquences allant de frais bancaires supplémentaires jusqu'à un incident Banque de France.
                    </strong>
                </li>
            </ul>
        </div>
    </li>
    <li style="background-color: #fff; min-height: 25px;">&nbsp;</li>
    <p><center><?php echo $this->showText(); ?></center></p>
    <?php 
    //dont show password field if user is logged in OR email is is already registered in system (when user checkout as guest)
    if($this->showPassword()):
    ?>
    <li class="adyen_payment_input_fields">
        <label for="<?php echo $_code ?>_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
        <div class="input-box">
            <input type="password" id="<?php echo $_code ?>_password" name="payment[password]"  title="<?php echo $this->__('Password') ?>" class="input-text validate-password required-entry" value="" placeholder=" Minimum 6 caractères " />
        </div>
    </li>
    <?php endif; ?>
    <li class="adyen_payment_creditcard_labels">
    <div style="margin: 0 auto; max-width: 450px;">
        <?php $count = 0;
        $ccTypes = $this->getCcAvailableTypes();
        foreach ($ccTypes as $_typeCode => $_typeName): 
           if ($_typeName != 'Maestro') :  ?>
            <?php $_filename = $this->getSkinUrl('images/adyen/' . strtolower($_typeCode) . '_small.png'); ?>
            <img id="cc_installment_type_<?php echo $count; ?>" width="40" height="22" src="<?php echo $_filename; ?>" alt="" class="mid" />
            <?php ++$count; 
           endif;
        endforeach; ?></div>
        <input type="hidden" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" value=""/>
    </li>
    <li class="adyen_payment_input_fields">
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_number]\"" : " data-encrypted-name-cc=\"number\""); ?> title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-type required-entry" value="" maxlength="23"/>
        </div>
    </li>
    <li class="adyen_payment_input_fields">
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_owner]\"" : "data-encrypted-name-cc=\"holderName\""); ?> value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" maxlength="100" />
        </div>
    </li>
    <li class="adyen_payment_input_fields">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_exp_month]\"" : "data-encrypted-name-cc=\"expiryMonth\""); ?> class="month validate-cc-exp validate-adyen required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_exp_year]\"" : "data-encrypted-name-cc=\"expiryYear\""); ?> class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>

    <?php if($this->hasVerification()): ?>
    <li class="adyen_payment_input_fields">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-digits validate-length" id="<?php echo $_code ?>_cc_cid" <?php echo (!$this->isCseEnabled() ? "name=\"payment[cc_cid]\"" : "data-encrypted-name-cc=\"cvc\""); ?> value="" size="7" maxlength="4" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
    <?php /*if($this->hasInstallments()): ?>
    <li class="adyen_payment_input_fields">
        <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_installments" name="payment[additional_data]" class="number required-entry">
                    <?php foreach ($this->getPossibleInstallments() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php endif;*/?>
    <input type="hidden" name="payment[additional_data]" id="<?php echo $_code ?>_installments" value="3">

    <?php if($this->canCreateBillingAgreement()): ?>
    <li id="adyen-cc-remember-these-details" class="adyen_payment_input_fields">
        <div class="input-box">
            <div class="v-fix">
                <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc" value="1" checked />
                <label for="<?php echo $_code ?>_store_cc"><em>*</em><?php echo $this->__('Remember these details') ?></label>
            </div>
        </div>
    </li>
    <script type="text/javascript">
        // don't show save cc for quest checkout. Only possible to detect with javascript
        if ($('login:guest') && $('login:guest').checked) {
            $('adyen-cc-remember-these-details').hide();
        }
    </script>
    <?php endif; ?>

    <script type="text/javascript">    
        
        var group_types = [];
        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
        group_types.push("<?php echo $_typeCode; ?>");
        <?php endforeach ?>

        card_previousCardNumber = "";

        function selectBrand() {

            cardNumber = (document.getElementById( '<?php echo $_code ?>_cc_number' ).value);
            dontHideErrorFrame = null;

            // empty card field - reset all
            if (cardNumber.length == 0) {
                card_previousCardNumber = cardNumber;
                cardSetCardBrand(null, false, group_types);
                return;
            }

            // When editing the card (but not adding digits at the end), don't reformat the number
            var l=0;
            while(l < card_previousCardNumber.length && l < cardNumber.length) {
                if(cardNumber[l] != card_previousCardNumber[l]) {
                    card_previousCardNumber = cardNumber;
                    return;
                }
                l++;
            }

            // remove all whitespace
            reg = /\s+/g;
            cardNumber = cardNumber.replace(reg,'');

            nrOfDigits = cardNumber.length;
            if(nrOfDigits > 19){
                return;
            }

            baseCard = getBaseCard(cardNumber, group_types);

            if(baseCard != null) {
                cardSetCardBrand(baseCard, true, group_types);
            } else if(nrOfDigits > 4) {
                cardSetCardBrand(null, true, group_types);
            } else {
                cardSetCardBrand(null, false, group_types);
            }

            //show value with white space after four numbers
            result = cardNumber.replace(/(\d{4})/g, '$1 ');
            result = result.replace(/\s+$/, ''); //remove trailing spaces
            card_previousCardNumber = result;
            document.getElementById( '<?php echo $_code; ?>_cc_number' ).value = result;
        }

        function cardSetCardBrand(selectedCard, greyInactive, group_types) {

            for(var i = 0; i < group_types.length; ++i) {
                var imageId =  'cc_installment_type_'  + i;
                if(selectedCard != null && group_types[i] == selectedCard.cardtype) {
                    // remove class
                    $(imageId).removeClassName('grey');
                    // set hidden field cc type for installments
                    $('<?php echo $_code ?>_cc_type').setValue(selectedCard.cardtype);
                } else {
                    if(greyInactive) {
                        // add class
                        $(imageId).addClassName('grey');
                    } else {
                        // remove class
                        $(imageId).removeClassName('grey');
                    }
                }
                document.getElementById(imageId).style.display="inline";
            }

            <?php if($this->hasInstallments()): ?>
            if(selectedCard != null ) {
                var interval = setInterval(getInstallments(selectedCard.cardtype), 500);
            }
            <?php endif; ?>

            cardSetCvcElementselectedCardType(selectedCard != null ? selectedCard.cardtype : null);

        }

        function cardSetCvcElementselectedCardType(selectedCardType) {
            var cvcCodeElem = document.getElementById( '<?php echo $_code; ?>_cc_cid' );

            // first remove classnames
            if(cvcCodeElem != null) {
                cvcCodeElem.removeClassName('maximum-length-3');
                cvcCodeElem.removeClassName('minimum-length-3');
                cvcCodeElem.removeClassName('maximum-length-4');
                cvcCodeElem.removeClassName('minimum-length-4');
            }

            if(selectedCardType == null) {
                // error do nothing
            } else if(selectedCardType == "AE") {
                cvcCodeElem.maxLength = 4;
                cvcCodeElem.addClassName('maximum-length-4');
                cvcCodeElem.addClassName('minimum-length-4');
            } else {
                cvcCodeElem.maxLength = 3;
                cvcCodeElem.addClassName('maximum-length-3');
                cvcCodeElem.addClassName('minimum-length-3');
            }
        }

        var ajaxReq;
        function getInstallments(variant) {

            // get the installments for this cardtype
            var ccType = variant;

            var url = '<?php echo $this->getUrl('adyen/GetInstallments', array('_secure'=>true)); ?>';

            if(ajaxReq && ajaxReq.readystate != 4){
                ajaxReq.transport.abort();
            }

            ajaxReq = new Ajax.Request(url, {
                parameters: {ccType: ccType, isAjax: 1, method: 'POST'},
                onSuccess: function(transport) {

                    if(transport.status == 200) {

                        // get current selected installment
                        var currentSelectedInstallment = document.getElementById('<?php echo $_code ?>_installments').getValue();

                        // clear the select box
                        document.getElementById('<?php echo $_code ?>_installments').options.length = 0;

                        var response = transport.responseText.evalJSON();

                        var sel = false;
                        for (var key in response) {

                            // change the installments
                            var opt = document.createElement('option');
                            opt.text = response[key]
                            opt.value = key;
                            // check if selected installment is still available
                            if(currentSelectedInstallment == key) {
                                sel = true;
                            }
                            $('<?php echo $_code ?>_installments').options.add(opt);
                        }

                        if(sel == true && currentSelectedInstallment) {
                            document.getElementById('adyen_cc_installments').value=currentSelectedInstallment;
                        }
                    }
                },
                onFailure: function(){
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                }
            });
        }

        // default
        window.onload = function(){
            cardSetCardBrand(null, false, group_types);
        }

        // observers
        Event.observe($('<?php echo $_code ?>_cc_number'), 'change', selectBrand);
        Event.observe($('<?php echo $_code ?>_cc_number'), 'keyup', selectBrand);

    </script>

    <?php if ($this->isCseEnabled()): ?>
        <input type="hidden" id="payment_encrypted_data_<?php echo $_code;?>" name="payment[encrypted_data]" value=""/>
        <input type="hidden" id="<?php echo $_code ?>_encrypted_form_expiry_generationtime" value="<?php echo date("c"); ?>" data-encrypted-name-cc="generationtime" />
        <script type="text/javascript">

            // get closest form element
            var element = $('payment_form_<?php echo $_code ?>');
            var form =  element.match('form') ? element : element.up('form');
            var cse_key = <?php echo json_encode($this->getCsePublicKey()); ?>;
            var cse_options = {
                name:  'payment_encrypted_data_<?php echo $_code;?>'
            };

            var cseUpdate = function() {
                try {
                    if (payment.currentMethod && payment.currentMethod == '<?php echo $_code ?>') {
                        // get closest form element
                        var elementCc = $('payment_form_<?php echo $_code ?>');
                        var cse_form =  elementCc.match('form') ? elementCc : elementCc.up('form');
                        // add this field to option
                        cse_options.fieldNameAttribute = "data-encrypted-name-cc";

                        // do not validate because number does not exists for oneclick
                        cse_options.enableValidations = false;

                        var cseForm = adyen.encrypt.createEncryptedForm(cse_form, cse_key, cse_options);
                        // encrypt data directly because submit button is not always on the page
                        cseForm.createEncryptedField(cseForm.encrypt());
                    }
                } catch (e) {
                    if (typeof console == "object") {
                        console.error(e);
                    } else {
                        alert("Warning: Adyen Client Side Encryption cannot succeed.");
                    }
                }

            };

            var cseInit = function() {
                if (typeof adyen === 'undefined') {
                    var script = document.createElement("script");
                    script.type = "text/javascript";
                    script.src = "<?php echo $this->getJsUrl('adyen/payment/adyen.encrypt_0_1_16.js'); ?>";
                    document.body.appendChild(script);
                }

                // if the browser does not support forach method implement it
                if (!Array.prototype.forEach) {
                    Array.prototype.forEach = function(fn, scope) {
                        for(var i = 0, len = this.length; i < len; ++i) {
                            fn.call(scope, this[i], i, this);
                        }
                    }
                }

                var fields = $$('#payment_form_<?php echo $_code ?> input, #payment_form_<?php echo $_code ?> textarea, #payment_form_<?php echo $_code ?> select');
                fields.forEach(function(field) {
                    field.observe('change', cseUpdate);

                    // the creditcard field needs to be updated on keyup as well
                    // old browsers don't allow keyup and change event and because the cardBrand logo is shown
                    // on keyup we need to update the CSE as well on keyup for creditcard number
                    if(field.id == "<?php echo $_code ?>_cc_number") {
                        field.observe('keyup', cseUpdate);
                    }
                });
            };

            cseInit();
        </script>
    <?php endif;?>
</ul>
