<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */

?>
<?php
/** @var Adyen_Payment_Block_Form_Oneclick $this */
$_code = $this->getMethodCode();
$_recurringDetails = $this->getRecurringDetails();
$originKey = $this->getOriginKey();
?>
<fieldset id="" class="">
    <ul class="form-list adyen_oneclick" id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php if (isset($_recurringDetails["card_number"]) && isset($_recurringDetails["card_expiryMonth"]) && isset($_recurringDetails["card_expiryYear"])): ?>
                <div class="checkout-oneclick-container">
                    <div id="oneclick-div-<?php echo $_code ?>" class="oneclick-div">
                        <div class="js-chckt-pm__pm-holder">
                            <input type="hidden" name="txvariant" value="oneclick_<?php echo $_code; ?>"/>
                        </div>
                    </div>
                    <?php if ($this->showCvc() && $_recurringDetails["variant"] !== "bcmc"): ?>
                        <input type="hidden" class="required-entry" name="payment[encrypted_cvc_<?php echo $_code; ?>]"
                               id="encryptedSecurityCode<?php echo $_code; ?>"
                               value="">
                        <div class="validation-advice"
                             id="advice-required-entry-encryptedSecurityCode<?php echo $_code; ?>"
                             style="display: none;"><?php echo $this->__('This is a required field.') ?></div>
                    <?php endif; ?>
                </div>
            <?php if ($this->hasInstallments()): ?>
                <div id="adyen_oneclick_installment_<?php echo $_code; ?>" class="adyen-oneclick-installments">
                    <label for="<?php echo $_code ?>_installment_<?php echo $_code; ?>"
                           class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_installment" name="payment[installment]"
                                    class="adyen-installment number required-entry">
                                <?php foreach ($this->getInstallments() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

                <script type="text/javascript">

                    function polyFill() {
                        if (Array.prototype.filter) {
                            Array.prototype.filter = function (func, thisArg) {
                                'use strict';
                                if (!((typeof func === 'Function' || typeof func === 'function') && this))
                                    throw new TypeError();

                                var len = this.length >>> 0,
                                    res = new Array(len), // preallocate array
                                    t = this, c = 0, i = -1;
                                if (thisArg === undefined) {
                                    while (++i !== len) {
                                        // checks to see if the key was set
                                        if (i in this) {
                                            if (func(t[i], i, t)) {
                                                res[c++] = t[i];
                                            }
                                        }
                                    }
                                } else {
                                    while (++i !== len) {
                                        // checks to see if the key was set
                                        if (i in this) {
                                            if (func.call(thisArg, t[i], i, t)) {
                                                res[c++] = t[i];
                                            }
                                        }
                                    }
                                }

                                res.length = c; // shrink down array to proper size
                                return res;
                            };
                        }
                    }

                    /**
                     * Renders the secure CVC field,
                     * creates the card component,
                     * sets up the callbacks for card components
                     */
                    function renderSecureCVC() {
                        var locale = "<?php echo Mage::app()->getLocale()->getLocaleCode();?>";
                        var variant = "<?php echo $_recurringDetails["variant"]?>";
                        var oneClickCardNode = document.getElementById('oneclick-div-<?php echo $_code ?>');

                        var checkout = new AdyenCheckout({
                            locale: locale,
                            originKey: "<?php echo $originKey;?>",
                            loadingContext: "<?php echo Mage::helper('adyen')->getCheckoutContextUrl();?>"
                        });
                        var hideCVC = false;
                        if ("<?php echo $this->showCvc();?>") {
                            if (variant == "bcmc") {
                                hideCVC = true;
                            } else if (variant == "maestro") {
                                document.getElementById('encryptedSecurityCode<?php echo $_code; ?>').classList.remove("required-entry");
                            }
                        } else {
                            hideCVC = true;
                        }
                        var oneClickCard = checkout
                            .create('card', {
                                type: variant,
                                oneClick: true,
                                hideCVC: hideCVC,

                                // Specific for oneClick cards
                                details: [
                                    {
                                        "key": "cardDetails.cvc",
                                        "type": "cvc"
                                    }
                                ],
                                storedDetails: {
                                    "card": {
                                        "expiryMonth": <?php echo $_recurringDetails["card_expiryMonth"]?>,
                                        "expiryYear": <?php echo $_recurringDetails["card_expiryYear"]?>
                                    }
                                },

                                onChange: function (state, component) {
                                    if (hideCVC) {
                                        return;
                                    }
                                    if (variant == "maestro"){
                                        if(component.state.errors.encryptedSecurityCode) {
                                            document.getElementById('encryptedSecurityCode<?php echo $_code; ?>').classList.add("required-entry");
                                        }
                                        else {
                                            document.getElementById('encryptedSecurityCode<?php echo $_code; ?>').classList.remove("required-entry");
                                        }
                                    }
                                    if (state.isValid && state.data.encryptedSecurityCode) {
                                        document.getElementById('encryptedSecurityCode<?php echo $_code; ?>').value = state.data.encryptedSecurityCode;
                                    } else {
                                        document.getElementById('encryptedSecurityCode<?php echo $_code; ?>').value = '';
                                    }

                                }
                            })
                            .mount(oneClickCardNode);
                    }

                    var secf = document.createElement("script");
                    <?php $adyenHelper = Mage::helper('adyen'); ?>
                    secf.src = "<?php echo $adyenHelper->getCheckoutCardComponentJs();?>";
                    secf.type = "text/javascript";
                    secf.onload = function () {
                        polyFill();
                        renderSecureCVC();
                    };
                    document.body.appendChild(secf);
                </script>

            <?php elseif (isset($_recurringDetails["variant"]) && $_recurringDetails["variant"] == "elv"): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Account holder name') ?></label>
                    <span><?php echo $_recurringDetails["elv_accountHolderName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('Account Number') ?></label>
                    <span><?php echo $_recurringDetails["elv_bankAccountNumber"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Bank Name') ?></label>
                    <span><?php echo $_recurringDetails["elv_bankName"]; ?></span>
                </div>
            <?php elseif (isset($_recurringDetails["variant"]) && $_recurringDetails["variant"] == "openinvoice"): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Bank account holder name') ?></label>
                    <span><?php echo $_recurringDetails["bank_ownerName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('Bank Account Number') ?></label>
                    <span><?php echo $_recurringDetails["bank_bankAccountNumber"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Country') ?></label>
                    <span><?php echo $_recurringDetails["bank_countryCode"]; ?></span>
                </div>
            <?php elseif (isset($_recurringDetails["variant"]) && ($_recurringDetails["variant"] == "sepadirectdebit" || $_recurringDetails["variant"] == "ideal")): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Bank account holder name') ?></label>
                    <span><?php echo $_recurringDetails["bank_ownerName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('IBAN') ?></label>
                    <span><?php echo $_recurringDetails["bank_iban"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Country') ?></label>
                    <span><?php echo $_recurringDetails["bank_countryCode"]; ?></span>
                </div>
            <?php endif; ?>
        </li>
    </ul>
</fieldset>

