<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */

?>
<?php
/** @var Adyen_Payment_Block_Form_Oneclick $this */
$_code = $this->getMethodCode();
$_recurringDetails = $this->getRecurringDetails();
$originKey = $this->getOriginKey();
?>
<fieldset id="" class="">
    <ul class="form-list adyen_oneclick" id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php if (isset($_recurringDetails["card_number"]) && isset($_recurringDetails["card_expiryMonth"]) && isset($_recurringDetails["card_expiryYear"])): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Credit Card Number') ?></label>
                    <span><?php echo $this->__('**** **** **** %s', $_recurringDetails["card_number"]); ?></span>
                </div>

                <div class="columns three b">
                    <label><?php echo $this->__('Expiration Date') ?><a href="#"
                                                                        id="update-expiration-date-<?php echo $_code; ?>"
                                                                        class="update-expiration-date"><?php echo $this->__('(update)') ?></a></label>

                    <div id="static-card-expiry-<?php echo $_code; ?>" class="static-card-expiry">
                        <?php echo $_recurringDetails["card_expiryMonth"] . " / " . $_recurringDetails["card_expiryYear"]; ?>
                    </div>
                    <div id="changable-card-expiry-<?php echo $_code; ?>" class="changable-card-expiry"
                         style="display:none;">
                        <select id="<?php echo $_code ?>_expiration_<?php echo $_code; ?>" <?php echo("data-encrypted-name-oneclick-" . $_code . "=expiryMonth"); ?>
                                class="month validate-oneclick-exp required-entry">
                            <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_recurringDetails["card_expiryMonth"]): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>

                        <select id="<?php echo $_code ?>_expiration_yr_<?php echo $_code; ?>" <?php echo("data-encrypted-name-oneclick-" . $_code . "=expiryYear"); ?>
                                class="year required-entry">
                            <?php foreach ($this->getCcYears() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_recurringDetails["card_expiryYear"]): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>

            <?php if ($this->hasInstallments()): ?>
                <div id="adyen_oneclick_installment_<?php echo $_code; ?>" class="adyen-oneclick-installments">
                    <label for="<?php echo $_code ?>_installment_<?php echo $_code; ?>"
                           class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_installment" name="payment[installment]"
                                    class="adyen-installment number required-entry">
                                <?php foreach ($this->getInstallments() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

                <div class="checkout-oneclick-container">
                    <div id="oneclick-div-<?php echo $_code ?>" class="oneclick-div">
                        <div class="js-chckt-pm__pm-holder">
                            <input type="hidden" name="txvariant" value="oneclick_<?php echo $_code; ?>"/>
                            <div id="update-exp-date-<?php echo $_code; ?>" style="display: none">
                                <div class="input-container">
                                    <span class="input-label">Expiry month:</span>
                                    <span class="input-field" data-cse="encryptedExpiryMonth"></span>
                                </div>
                                <div class="input-container">
                                    <span class="input-label">Expiry year:</span>
                                    <span class="input-field" data-cse="encryptedExpiryYear"></span>
                                </div>
                            </div>
                            <div class="input-container">
                                <span class="input-label label-security-code">Security code:</span>
                                <span class="input-field" data-cse="encryptedSecurityCode"></span>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="payment[encrypted_expiry_month_<?php echo $_code; ?>]"
                           id="encryptedExpiryMonth<?php echo $_code; ?>" value="">
                    <input type="hidden" name="payment[encrypted_expiry_year_<?php echo $_code; ?>]"
                           id="encryptedExpiryYear<?php echo $_code; ?>" value="">
                    <input type="hidden" name="payment[encrypted_cvc_<?php echo $_code; ?>]"
                           id="encryptedSecurityCode<?php echo $_code; ?>"
                           value="">

                </div>

                <script type="text/javascript">

                    // On radio button, hide the date(if present) and show the href
                    Event.observe($("p_method_<?php echo $_code; ?>"), 'change', function () {
                        $("update-exp-date-<?php echo $_code; ?>").hide();
                        $("update-expiration-date-<?php echo $_code; ?>").show();
                    });

                    // update-expiration-date action
                    $$('#update-expiration-date-<?php echo $_code; ?>').each(function (element) {
                        element.observe('click', updateExpirationDate);
                    });
                    function updateExpirationDate(event) {
                        // hide the link
                        this.hide();
                        // show expiration month and year/changeable card expiry
                        $("update-exp-date-<?php echo $_code; ?>").show();
                        event.preventDefault();
                    }

                </script>

            <?php elseif (isset($_recurringDetails["variant"]) && $_recurringDetails["variant"] == "elv"): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Account holder name') ?></label>
                    <span><?php echo $_recurringDetails["elv_accountHolderName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('Account Number') ?></label>
                    <span><?php echo $_recurringDetails["elv_bankAccountNumber"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Bank Name') ?></label>
                    <span><?php echo $_recurringDetails["elv_bankName"]; ?></span>
                </div>
            <?php elseif (isset($_recurringDetails["variant"]) && $_recurringDetails["variant"] == "openinvoice"): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Bank account holder name') ?></label>
                    <span><?php echo $_recurringDetails["bank_ownerName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('Bank Account Number') ?></label>
                    <span><?php echo $_recurringDetails["bank_bankAccountNumber"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Country') ?></label>
                    <span><?php echo $_recurringDetails["bank_countryCode"]; ?></span>
                </div>
            <?php elseif (isset($_recurringDetails["variant"]) && ($_recurringDetails["variant"] == "sepadirectdebit" || $_recurringDetails["variant"] == "ideal")): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Bank account holder name') ?></label>
                    <span><?php echo $_recurringDetails["bank_ownerName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('IBAN') ?></label>
                    <span><?php echo $_recurringDetails["bank_iban"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Country') ?></label>
                    <span><?php echo $_recurringDetails["bank_countryCode"]; ?></span>
                </div>
            <?php endif; ?>
        </li>
    </ul>
</fieldset>

