<?php
/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Adyen
 * @package    Adyen_Payment
 * @copyright    Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2018 Adyen BV (http://www.adyen.com)
 */
?>
<?php $_code = $this->getMethodCode() ?>

<script type="text/javascript">
    //To be optimized in PW-599
    $("initiate").on("click",function () {
        new Ajax.Request("<?php echo $this->getUrl('adyen/Pos/initiate', array('_secure' => true)); ?>", {
            parameters: {isAjax: 1, method: 'POST'},
            onSuccess: function (response) {
                console.log(response.responseText);
                if (response.responseText.indexOf("Timeout") > -1) {
                   status();
                }
                return;
            },
            onFailure: function () {
                reject(Error("Network Error"));
            }
        });
    });
    function status(){
        new Ajax.Request("<?php echo $this->getUrl('adyen/Pos/checkStatus', array('_secure' => true)); ?>", {
            parameters: {isAjax: 1, method: 'POST'},
            onSuccess: function (response) {
                console.log(response.responseText);
                setTimeout(
                    status,5000);
            },
            onFailure: function () {
                reject(Error("Network Error"));
            }
        });
    };
</script>

<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>

            <input type="button" id="initiate" value="Initiate"
                   class="button btn-proceed-checkout btn-checkout adyen-checkout-button"/>

        </li>
    </ul>
</fieldset>

