<?php

/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php if($this->hasExpressCheckout() || $this->hasCashExpressCheckout() ): ?>



    <div id="adyen-checkout-wrapper" style="">
        <form class="form-list" action="<?php echo $this->getUrl("adyen/checkoutPos", array('_secure'=>true)); ?>" method="post">


            <div class="adyenExpressCheckoutBlockLeft">
                <input style="width:240px;" type="text" class="input-text" name="adyenPosEmail" id="adyenPosEmail" value="<?php echo $this->getEmailAddressShopper(); ?>" size="60"  placeholder="Email" autocapitalize="off" autocomplete="off"/>

<!--                <select id="adyenPosPaymentDevices">-->
<!--                </select>-->

                <div id="autocomplete_choices" class="adyenAutocomplete" style="display: none;"></div>

                <div class="input-box">
                    <div class="v-fix">
                        <input type="checkbox" class="checkbox" name="adyenPosSaveCard" id="adyenPosSaveCard" checked/>
                        <label for="adyenPosSaveCard"><?php echo $this->__('Save Card'); ?></label>
                    </div>
                </div>

                <div id="adyenEmailLoader" class="autocomplete-indicator" style="display: none;">
                    <img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading...') ?>" class="v-middle"/>
                </div>

                <div id="AdyenAccountInfo"></div>
            </div>

            <?php if($this->hasExpressCheckout() && $this->inKioskMode() != "1"): ?>

                <script type="text/javascript">
                    $('adyenPosEmail').observe('change', getCustomerFromEmail);
                    $('adyenPosEmail').observe('keyup', enablePOSButton);

                    new Ajax.Autocompleter(
                        'adyenPosEmail',
                        'autocomplete_choices',
                        '<?php echo $this->getUrl('adyen/checkoutPos/getCustomerEmail') ?>',
                        {
                            paramName:"email",
                            minChars:2,
                            indicator:"adyenEmailLoader",
                            evalJSON:'force',
                            afterUpdateElement : getSelectionId
                        }
                    );

                    function getSelectionId(text, li) {
                        // strip of customer- to get the id
                        var id = li.id;
                        var customerId = id.replace("customer-", "");
                        getCustomerFromEmailAjaxCall(null, customerId);
                    }

                    function enablePOSButton(event) {
                        if(this.value != "") {
                            document.getElementById('CheckoutWithPos').disabled = false;
                        } else {
                            document.getElementById('CheckoutWithPos').disabled = true;
                        }
                    }

                    function getCustomerFromEmail(event) {
//                        getCustomerFromEmailAjaxCall(this.value, null);
                        // clear info
                        $('AdyenAccountInfo').update("");

                    }

                    function getCustomerFromEmailAjaxCall(email, customerId) {

                        // clear info
                        $('AdyenAccountInfo').update("");

                        var url = '<?php echo $this->getUrl('adyen/checkoutPos/validateCustomerByEmail', array('_secure'=>true));?>';

                        ajaxReq = new Ajax.Request(url, {
                            parameters: {email: email, customerId: customerId, isAjax: 1, method: 'POST'},
                            onSuccess: function(transport) {

                                if(transport.status == 200) {
                                    var json = transport.responseText.evalJSON();
                                    if(json) {

                                        var text = "<div class=\"AdyenShopperDetails\"><h3><?php echo $this->__('Shopper Details') ?>:</h3>";
                                        text += "<?php echo $this->__('Firstname'); ?>: " + json.customerData.firstname;
                                        text+= "<br />";
                                        text += "<?php echo $this->__('Lastname'); ?>: " + json.customerData.lastname;
                                        text += "</div>";

                                        <?php if($this->showExpressCheckoutRecurringCards()): ?>
                                            var savedCards = false;
                                            if(json.recurringCards) {
                                                text += "<div class=\"AdyenSavedCards\"><h3><?php echo $this->__('Saved cards') ?>:</h3>";
                                                for (var i=0;i<json.recurringCards.length;i++)
                                                {
                                                    if(json.recurringCards[i].card_number)
                                                    {
                                                        savedCards = true;
                                                        var variant = json.recurringCards[i].variant;
                                                        var imageUrl = '<?php echo $this->getSkinUrl("images/adyen/elv.png"); ?>';
                                                        imageUrl = imageUrl.replace("elv", variant);
                                                        var html = '<div class="creditcard-block">';
                                                        html += '<a href="<?php echo $this->getUrl('adyen/checkoutPos', array('_secure'=>true));?>?recurringDetailReference=' + json.recurringCards[i].recurringDetailReference + '&customerId=' + json.customerData.entity_id + '">';
                                                        html += '<img src="'+ imageUrl + '" alt="' + variant + '" label="' + variant + '" />';
                                                        html += '</a>';
                                                        html += '<span> **** ' + json.recurringCards[i].card_number + '</span>';
                                                        html += ' ' + json.recurringCards[i].card_holderName;
                                                        html += '</div>';
                                                        text += html;
                                                    }
                                                }
                                                if(savedCards == false) {
                                                    text += "<div><?php echo $this->__('There are no saved cards for this account.');?></div>";
                                                }
                                                text += "</div>";
                                            }
                                        <?php endif; ?>
                                        $('AdyenAccountInfo').update(text);

                                    } else {
                                        $('AdyenAccountInfo').update("<?php echo $this->__('This is a new Customer'); ?>");
                                    }
                                }
                            },
                            onFailure: function(){
                                alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                            }
                        });
                    }
                </script>

            <?php endif; ?>
            
            <?php if($this->hasExpressCheckout()): ?>
                <button id="CheckoutWithPos" style="" type="submit" title="<?php echo $this->__($this->getExpressCheckoutTitle()); ?>" class="button btn-proceed-checkout btn-checkout adyen-checkout-button" disabled>
                    <span><span><?php echo $this->__($this->getExpressCheckoutTitle()); ?></span></span>
                </button>

                <script type="text/javascript">


//                    $('CheckoutWithPos').observe('click', doTransaction);
//
//                    function doTransaction(event) {
//                        if(adyenpos)
//                        {
//                            var request = {
//                                //terminalId: "test",
//                                amount: '50',
//                                currency: 'EUR',
//                                reference: '10000-test',
//                                callbackAutomatic: true
//                            };
//
//                            var terminalId = $('adyenPosPaymentDevices').getValue();
//
//                            if (terminalId) {
//                                request.terminalId = terminalId;
//                            }
//
//                            console.log(request);
//                            adyenpos.startTransaction(request, function(response){
//
//                                // redirect to success page
//                            });
//
//                            return false;
//                        }
//                    }
//                    
//                    function adyenposLoaded() {
//                        var devicesList = adyenpos.paymentDevices();
//
//                        setDropDown(
//                            $('adyenPosPaymentDevices'),
//                            devicesList,
//                            function(e) {
//                                return new Option( e.name, e.terminalId );
//                            }
//                        );
//                    }
//
//                    function setDropDown(field, data, method, index) {
//
//                        field.options.length = index == null ? 1 : index;
//                        data.each(
//                            function(e) {
//                                field.options.add(method(e));
//                            }
//                        );
//                    }



                </script>

            <?php endif; ?>

        </form>

        <?php if($this->hasCashExpressCheckout()): ?>
            <form id="AdyenFormCheckoutWithCash" action="<?php echo $this->getUrl("adyen/checkoutCash", array('_secure'=>true)); ?>" method="post">

                <button id="CheckoutWithCash" style="" type="submit" title="<?php echo $this->__($this->getCashExpressCheckoutTitle()); ?>" class="button btn-proceed-checkout btn-checkout adyen-checkout-button">
                    <span><span><?php echo $this->__($this->getCashExpressCheckoutTitle()); ?></span></span>
                </button>

            </form>
        <?php endif; ?>

<!--        <div>-OR-</div>-->

    </div>



    <script type="text/javascript">

        // if CheckoutWithPos not empty enable button
        if($('adyenPosEmail').value) {
            document.getElementById('CheckoutWithPos').disabled = false;
        }

        $$('.btn-proceed-checkout').last().update("Online checkout");

        // show CheckoutWithPos only if you fill in a email address


        // moved to scan_product this function can only be called once foreach page
//        function adyenposLoaded() {
//            // Show PIN checkout button
//            $("adyen-checkout-wrapper").show();
//
//            // hide normal checkout button
//            $$(".method-checkout-cart-methods-onepage-bottom").each(Element.hide);
//        }

    </script>



<?php endif; ?>