<?php

/**
 * Adyen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Adyen
 * @package	Adyen_Payment
 * @copyright	Copyright (c) 2011 Adyen (http://www.adyen.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php if($this->hasEnableScanner()): ?>
    <div id="adyenCustomScanWrapper">
        <form id="addToCartBarCode" method='post' action="<?php echo  $this->getUrl("adyen/updateCart/index", array('_secure'=>true)); ?>">
        </form>


        <script type="text/javascript">


            var intervalId;
            var scanInProgress = false;



            function adyenposLoaded() {

                // set title checkout different for now

                // Show PIN checkout button
                // $("adyen-checkout-wrapper").show();

                // hide normal checkout button
                // $$(".method-checkout-cart-methods-onepage-bottom").each(Element.hide);

                adyenpos.on("barcodeReceived", function(barcode) {
                    ajaxCall(barcode);
                });
            }
            // check if scan is done with scanning
            function checkValueInput(value) {

                var currentValue = $('inpscan').value;

                if(value == currentValue) {
                    // DO ajax call
                    ajaxCall(value);
                    this.scanInProgress = false;
                    return;
                }

                // call same function after certain period of time
                var test = setTimeout("checkValueInput($('inpscan').value)", 100);
            }


            function scan() {

                if(this.scanInProgress === false) {

                    // get value
                    var value = $('inpscan').value;
                    if(value) {
                        this.scanInProgress = true;

                        // extra check for full input from scanner
                        setTimeout("checkValueInput($('inpscan').value)", 250);
                    }
                }
            }

            function ajaxCall(code) {

                var form = document.getElementById("addToCartBarCode");
                new Ajax.Request(form.action, {
                    parameters: {code: code, isAjax: 1, method: 'POST'},
                    onSuccess: function(transport) {

                        var response = transport.responseText;
                        // update
                        $$('.main_area').each(
                            function (e) {
                                e.update(response);

                                // temp change title:
                                if($$('.btn-proceed-checkout') && $$('.btn-proceed-checkout').last()) {
                                    $$('.btn-proceed-checkout').last().update("Online checkout");
                                }


                            }
                        );
                    },
                    onFailure: function(){
                        alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                    }
                });

            }
        </script>
    </div>
<?php endif; ?>